# Generated by Django 2.0.4 on 2018-06-05 23:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('cellphone', models.CharField(max_length=50)),
                ('mg_imei', models.CharField(max_length=50, unique=True)),
                ('mg_phone', models.CharField(max_length=50, unique=True)),
                ('year', models.CharField(max_length=4)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('emergency_name', models.CharField(max_length=100)),
                ('emergency_number', models.CharField(max_length=50)),
                ('sensitivity', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('trip_tracking', models.BooleanField()),
                ('anti_theft', models.BooleanField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Leads',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification_type', models.CharField(max_length=150)),
                ('lat', models.CharField(max_length=50)),
                ('lng', models.CharField(max_length=50)),
                ('device_IMEI', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('trip_number', models.CharField(max_length=150)),
                ('speed', models.CharField(max_length=50)),
                ('lean_angle', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=50)),
                ('lng', models.CharField(max_length=50)),
                ('device_IMEI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Device', to_field='mg_imei')),
            ],
        ),
    ]
