# Generated by Django 2.0.4 on 2018-06-05 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='device',
            new_name='device_IMEI',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='device',
            new_name='device_IMEI',
        ),
    ]
