# Generated by Django 2.0.4 on 2018-05-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leads',
            options={},
        ),
    ]
