# Generated by Django 2.0.4 on 2018-06-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180605_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
