# Generated by Django 2.0.4 on 2018-05-01 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180430_0425'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='Emails',
        ),
    ]
