# Generated by Django 2.0.4 on 2018-06-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180606_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
