# Generated by Django 2.0.4 on 2018-05-03 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180502_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
