# Generated by Django 2.0.4 on 2018-06-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180606_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='lat',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='lng',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
