# Generated by Django 2.0.4 on 2018-05-31 02:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180529_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('distance_traveled', models.CharField(max_length=50)),
                ('max_speed', models.CharField(max_length=50)),
                ('max_leanAngle', models.CharField(max_length=50)),
                ('device', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Device')),
            ],
        ),
    ]
