# Generated by Django 2.0.4 on 2018-06-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='first_name',
            field=models.CharField(default='N/A', max_length=150),
        ),
        migrations.AddField(
            model_name='device',
            name='last_name',
            field=models.CharField(default='N/A', max_length=150),
        ),
    ]
