# Generated by Django 2.0.4 on 2018-06-02 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180602_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='current_location',
        ),
    ]
