# Generated by Django 2.0.4 on 2018-06-04 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_device_current_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='time_stamp',
            new_name='date_time',
        ),
    ]
